const api = [
    {
        "title": "First Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    },
    {
        "title": "Second Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    },
    {
        "title": "Third Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    },
    {
        "title": "Fourth Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    },
    {
        "title": "Fifth Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    },
    {
        "title": "Sixth Title",
        "content": "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam accusamus vero excepturi atque optio, officiis inventore dolorem quam! Minus reprehenderit ut dolorem harum? Fugiat magnam placeat facilis repellat, error quae. Harum, neque corrupti? Alias voluptates enim, cum officia cupiditate quae repudiandae facilis qui esse quas hic quam, nesciunt quod consectetur expedita delectus, voluptatum ea numquam. Dolorum quisquam ipsum repellat consectetur? Voluptates molestias repellat, neque ratione ipsum quisquam! Molestiae repudiandae atque commodi amet laboriosam voluptates debitis porro, provident voluptate soluta ratione ab fugiat maiores repellendus accusantium, dolor, eligendi aliquam libero vitae! Quas enim, adipisci necessitatibus minus nostrum illo incidunt quia omnis nam reiciendis repellendus. Maxime, alias accusamus magnam quos nulla ex ut nesciunt suscipit dolore inventore enim provident harum impedit eveniet? Dolores officia consequatur natus consectetur pariatur magni reprehenderit dolorum, rerum fugiat, libero, nobis sequi quod ratione dolor tempora assumenda provident facere nulla! Quo esse dolorum autem nam molestias quidem rem."
    }
]

export default api;